remove disableing LinuxExtensions (bug Eter#2563)

diff --git a/etercifs/etercifs.init b/etercifs/etercifs.init
--- a/etercifs/etercifs.init
+++ b/etercifs/etercifs.init
@@ -108,7 +108,7 @@ umount_cifs()
 mount_cifs()
 {
     echo -n "Mounting CIFS resources... "
-    mount -t cifs -a || { failure ; return 1; }
+    mount -t cifs -a -o noperm || { failure ; return 1; }
     success
 }
 
@@ -132,7 +132,7 @@ load_module()
     #        $INSMOD $MODULEPATH && { echo ; echo -n "    insmod $MODULEPATH" ; success ; return ; }
     #        echo -n "Incorrect module. Your system: " ; uname -a ; dmesg | tail -n2
     #fi
-    echo -n "$MODULENAME from Etersoft is not found,"
+    echo -n "$MODULENAME from Etersoft is not found, "
     echo -n "you can try compile it with 'service etercifs build' command."
     failure
 }
@@ -141,11 +141,11 @@ start()
 {
     load_module
     if is_moduled ; then
-        test -r /proc/fs/cifs/Etersoft 2>/dev/null || { echo -n "Check CIFS for Etersoft extensions... " ; failure ; return ; }
-        echo -n "Enable Etersoft extensions for CIFS..."
-        echo 1 > /proc/fs/cifs/Etersoft && success || failure
-        echo -n "Disable Linux extensions for CIFS..."
-        echo 0 > /proc/fs/cifs/LinuxExtensionsEnabled && success || failure
+#        test -r /proc/fs/cifs/Etersoft 2>/dev/null || { echo -n "Check CIFS for Etersoft extensions... " ; failure ; return ; }
+#        echo -n "Enable Etersoft extensions for CIFS..."
+#        echo 1 > /proc/fs/cifs/Etersoft && success || failure
+#        echo -n "Disable Linux extensions for CIFS..."
+#        echo 0 > /proc/fs/cifs/LinuxExtensionsEnabled && success || failure
         test -n "$WASCIFS" && mount_cifs || :
     else
         failure
@@ -177,12 +177,12 @@ status()
     fi
     if is_moduled ; then
         #echo "    kernel module $MODULENAME is loaded ($PRECOMP)"
-        test -d /proc/fs/cifs/ 2>/dev/null || { echo -n "Can't locale /proc/fs/cifs... " ; failure ; }
+#        test -d /proc/fs/cifs/ 2>/dev/null || { echo -n "Can't locale /proc/fs/cifs... " ; failure ; }
         echo "    kernel module $MODULENAME is loaded"
-        echo -n "Etersoft extensions for CIFS enabled..."
-        test "`cat /proc/fs/cifs/Etersoft 2>/dev/null`" = "1" && success || failure
-        echo -n "Unix extensions for CIFS disabled..."
-        test "`cat /proc/fs/cifs/LinuxExtensionsEnabled 2>/dev/null`" = "1" && failure || success
+#        echo -n "Etersoft extensions for CIFS enabled..."
+#        test "`cat /proc/fs/cifs/Etersoft 2>/dev/null`" = "1" && success || failure
+#        echo -n "Unix extensions for CIFS disabled..."
+#        test "`cat /proc/fs/cifs/LinuxExtensionsEnabled 2>/dev/null`" = "1" && failure || success
     else
         echo "    kernel module $MODULENAME is not loaded"
     fi
@@ -221,7 +221,8 @@ case "$1" in
     condrestart)
         # remove manual built module
         # rm -f $MANMODULEPATH
-        if [ "`cat /proc/fs/cifs/Etersoft 2>/dev/null`" = "1" ] ; then
+#        if [ "`cat /proc/fs/cifs/Etersoft 2>/dev/null`" = "1" ] ; then
+        if is_moduled ; then
             stop
             start
         else
